org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
# Si falla la descarga, cambia por la ultima 21.1.x de https://projects.neoforged.net/neoforged/neoforge
neo_version=21.1.172
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=tensuracraft
mod_name=TensuraCraft: Isekai Crossover
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.marcelo.tensuracraft
mod_authors=Marcelo
mod_description=Reencarnacion en otro mundo: razas, habilidades, gacha, evolucion, nombramientos, facciones de Tensura, Re:Zero, Overlord, Konosuba y Bleach.
